export default {
  Home: 'Home',
  Setting: 'Setting',
  Notification: 'Notification',
  Search: 'Search',
  Upload: 'Upload',
  Settings: 'Settings',
  ChangeTheme: 'ChangeTheme',
  Language: 'Language',
  Btabs: 'Btabs',
  Orders: 'Orserd',
  Profile: 'Profile',
  RestaurantDetail: 'RestaurantDetail',
  About: 'About',
  SoftDrisk: 'SoftDrisk',
  RestaurantItems: 'RestaurantItems',
  RoutesNAme: 'RoutesNAme',
};
